---
- name: Concourse CI
  hosts: localhost
  become: True
  become_user: "{{ username }}"
  tasks:
    - name: ensure the keys directories are present
      file: path=./keys/web
            state=directory

    - name: ensure the keys directories are present
      file: path=./keys/worker
            state=directory

    - name: ensure the generate script exists
      get_url:
        url: https://raw.githubusercontent.com/concourse/concourse-docker/master/keys/generate
        dest: ./keys/generate
        mode: 0777

    - name: check if ./concourse-keys dir exists
      stat: path=./concourse-keys
      register: keys_dir

    - name: create concourse keys if needed
      when: keys_dir.stat.isdir is not defined
      command: ./keys/generate

    - name: rename keys to concourse-keys
      when: keys_dir.stat.isdir is not defined
      command: mv ./keys ./concourse-keys

    - name: concourse db container
      become: True
      become_user: root
      docker_container:
        image: postgres
        name: concourse-db
        privileged: true
        env:
          POSTGRES_DB: concourse
          POSTGRES_PASSWORD: concourse_pass
          POSTGRES_USER: concourse_user
          PGDATA: /database

    - name: concourse web container
      become: True
      become_user: root
      docker_container:
        command: web
        image: concourse/concourse
        links: [concourse-db]
        name: concourse-web
        privileged: true
        ports: "8080"
        restart: yes
        restart_policy: unless-stopped
        volumes: 
          - ./concourse-keys/web:/concourse-keys
        env:
          CONCOURSE_ADD_LOCAL_USER: "test:test"
          CONCOURSE_EXTERNAL_URL: "https://ci.aliencyb.org"
          CONCOURSE_MAIN_TEAM_LOCAL_USER: "test"
          CONCOURSE_POSTGRES_DATABASE: "concourse"
          CONCOURSE_POSTGRES_HOST: "concourse-db"
          CONCOURSE_POSTGRES_PASSWORD: "concourse_pass"
          CONCOURSE_POSTGRES_USER: "concourse_user"
          CONCOURSE_TSA_PEER_ADDRESS: "https://ci.aliencyb.org"
          LETSENCRYPT_EMAIL: "ben@aliencyb.org"
          LETSENCRYPT_HOST: "ci.aliencyb.org"
          VIRTUAL_HOST: "ci.aliencyb.org"
          VIRTUAL_PORT: "8080"

    - name: concourse worker container
      become: True
      become_user: root
      docker_container:
        command: worker
        dns_servers: 8.8.8.8
        image: concourse/concourse
        links: [concourse-web]
        name: concourse-worker
        privileged: yes
        volumes:
          - ./concourse-keys/worker:/concourse-keys
        env:
          CONCOURSE_TSA_HOST: concourse-web

