---
- name: AlienCyborg DocuWiki
  hosts: localhost
  become: True
  tasks:
    - name: dokuwiki data container
      docker_container:
        image: bitnami/dokuwiki:0
        name: cyborg-dokuwiki-data
        state: present
        volumes:
          - /bitnami

    - name: dokuwiki container
      docker_container:
        image: bitnami/dokuwiki:0
        name: cyborg-dokuwiki
        state: started
        env:
          DOKUWIKI_USERNAME: benjamin
          DOKUWIKI_FULL_NAME: Benjamin Rosas
          DOKUWIKI_PASSWORD: supersecret
          DOKUWIKI_EMAIL: ben@aliencyb.org
          DOKUWIKI_WIKI_NAME: AlienCyborg DokuWiki
          LETSENCRYPT_EMAIL: 'admin@aliencyb.org'
          LETSENCRYPT_HOST: 'wiki.aliencyb.org'
          VIRTUAL_HOST: 'wiki.aliencyb.org'
        exposed:
          - 80
          - 443
        volumes:
          - cyborg-dokuwiki-data:/bitnami
