---
- name: Demo Drupal
  hosts: localhost
  become: True
  tasks:
    - name: drupal-demo backups container
      docker_container:
        image: mariadb:10
        name: drupal-demo-db-backups
        state: present
        volumes:
          - /backups

    - name: drupal-demo content container
      docker_container:
        image: drupal:8
        name: drupal-demo-content
        state: present
        volumes:
          - /var/www/html

    - name: drupal-demo data container
      docker_container:
        image: mariadb:10
        name: drupal-demo-db-data
        state: present
        volumes:
          - /var/lib/mysql

    - name: drupal-demo db
      docker_container:
        env_file: drupal-demo.env
        image: mariadb:10
        name: drupal-demo-db
        state: started
        volumes:
          - drupal-demo-db-backups:/backups
          - drupal-demo-db-data:/var/lib/mysql

    - name: drupal-demo web
      docker_container:
        env_file: drupal-demo.env
        exposed:
          - 80
          - 443
        image: drupal:8
        name: drupal-demo-web
        restart: yes
        state: started
        env:
          LETSENCRYPT_EMAIL: 'admin@aliencyb.org'
          LETSENCRYPT_HOST: 'drupal-demo.aliencyb.org'
          VIRTUAL_HOST: 'drupal-demo.aliencyb.org'
        links:
          - "drupal-demo-db:mysql"
        volumes:
          - drupal-demo-content:/var/www/html

    - name: drupal-demo ftp
      docker_container:
        command: alien:$1$f2f365a3$.9/vP55lZKHOIXQUnrTcf1/:e:33:33
        image: atmoz/sftp:latest
        name: drupal-demo-ftp
        state: started
        ports:
          - "49327:22"
        volumes:
          - drupal-demo-content:/home/alien/upload


