---
- name: ShahbazShah Wordpress
  hosts: localhost
  become: True
  tasks:
    - name: shahbaz-shah backups container
      docker_container:
        image: mariadb:10.4
        name: shahbaz-shah-db-backups
        state: present
        volumes:
          - /backups

    - name: shahbaz-shah content container
      docker_container:
        image: wordpress:5.2.1
        name: shahbaz-shah-content
        state: present
        volumes:
          - /var/www/html

    - name: shahbaz-shah data container
      docker_container:
        image: mariadb:10.4
        name: shahbaz-shah-db-data
        state: present
        volumes:
          - /var/lib/mysql

    - name: shahbaz-shah db
      docker_container:
        env_file: shahbaz-shah.env
        image: mariadb:10.4
        name: shahbaz-shah-db
        state: started
        volumes:
          - shahbaz-shah-db-backups:/backups
          - shahbaz-shah-db-data:/var/lib/mysql

    - name: shahbaz-shah web
      docker_container:
        env_file: shahbaz-shah.env
        exposed:
          - 80
          - 443
        image: wordpress:5.2.1
        name: shahbaz-shah-wp
        restart: yes
        state: started
        env:
          LETSENCRYPT_EMAIL: 'ben@aliencyb.org'
          LETSENCRYPT_HOST: 'shahbazshah.net,www.shahbazshah.net'
          VIRTUAL_HOST: 'shahbazshah.net,www.shahbazshah.net'
        links:
          - "shahbaz-shah-db:mysql"
        volumes:
          - shahbaz-shah-content:/var/www/html

    - name: shahbaz-shah ftp
      docker_container:
        command: shahbaz:$1$nbquHESY$.KlulEhDTQ8l3dVnBkVLk.:e:33:33
        image: atmoz/sftp:latest
        name: shahbaz-shah-ftp
        state: started
        ports:
          - "49323:22"
        volumes:
          - shahbaz-shah-content:/home/shahbaz/upload
