---
- name: restart network
  notify:
    - restart networkd
    - restart resolved
    - restart sshd

- name: restart networkd
  action: service name=systemd-networkd
    state=restarted

- name: restart resolved
  action: service name=systemd-resolved
    state=restarted

- name: restart sshd
  action: service name=sshd.socket
    state=restarted
