---
- name: update OS to latest version
  swupd:
    update: yes

- name: install software bundles
  swupd:
    name: "{{ item }}"
  with_items:
    - containers-basic
    - mtr
    - sysadmin-remote
    - vim
