all:
  children:
    webservers:
      hosts:
        beast:
          ansible_host: 68.168.187.155
          ansible_port: 43722
          ansible_private_key_file: ~/.ssh/nova_rsa
          ansible_user: root
        toofan:
          ansible_host: 24.118.178.123
          ansible_port: 65522
          ansible_private_key_file: ~/.ssh/nova_rsa
          ansible_user: root
    archlinux:
      hosts:
        beast:
        toofan:
    east:
      hosts:
        toofan:
    west:
      hosts:
        beast:
