---
- name: ensure the /etc/docker directory is present
  file:
    path: /etc/docker
    state: directory

- name: copy daemon.json file
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: ensure the docker.service.d directory is present
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy override.conf file
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    src: override.conf

- name: add user to docker group
  user:
    append: yes
    name: "{{ username }}"
    groups:
      - docker

- name: enable docker service
  service:
    enabled: yes
    name: docker
    state: started
