---
- name: ensure the /etc/docker directory is present
  file:
    path: /etc/docker
    state: directory

- name: copy daemon.json file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: ensure the docker.service.d directory is present
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy override.conf file
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes