---
- name: install packages
  pacman:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ack
      - btrfs-progs
      - ctags
      - curl
      - docker
      - docker-compose
      - emacs
      - git
      - gptfdisk
      - htop
      - jnettop
      - openssh
      - reflector
      - rsync
      - sudo
      - tmux
      - tree
      - unzip
      - vim
      - wget
