---
- name: already-pres backups container
  docker_container:
    image: mariadb:10.2
    name: already-pres-db-backups
    state: present
    volumes:
      - /backups

- name: already-pres content container
  docker_container:
    image: wordpress:4.9
    name: already-pres-content
    state: present
    volumes:
      - /var/www/html

- name: already-pres data container
  docker_container:
    image: mariadb:10.2
    name: already-pres-db-data
    state: present
    volumes:
      - /var/lib/mysql

- name: already-pres db
  docker_container:
    env_file: already-pres.env
    image: mariadb:10.2
    name: already-pres-db
    state: started
    volumes:
      - already-pres-db-backups:/backups
      - already-pres-db-data:/var/lib/mysql

- name: already-pres web
  docker_container:
    env_file: already-pres.env
    exposed:
      - 80
      - 443
    image: wordpress:4.9
    name: already-pres-wp
    restart: yes
    state: started
    env:
      LETSENCRYPT_EMAIL: 'ben@aliencyb.org'
      LETSENCRYPT_HOST: 'iamalreadypresident.org,iamalreadypresident.com,iamalreadypresident.net,www.iamalreadypresident.org,www.iamalreadypresident.com,www.iamalreadypresident.net'
      VIRTUAL_HOST: 'iamalreadypresident.org,iamalreadypresident.com,iamalreadypresident.net,www.iamalreadypresident.org,www.iamalreadypresident.com,www.iamalreadypresident.net'
    links:
      - "already-pres-db:mysql"
    volumes:
      - already-pres-content:/var/www/html

#- name: already-pres ftp
  #docker_container:
    #command: rainy:$1$nbquHESY$.KlulEhDTQ8l3dVnBkVLk.:e:33:33
    #image: atmoz/sftp:latest
    #name: already-pres-ftp
    #state: started
    #ports:
      #- "49322:22"
    #volumes:
      #- already-pres-content:/home/rainy/upload
