---
- name: pull and run biscuitman
  docker_container:
    name: biscuitman
    image: aliencyborg/biscuitman-web
    pull: true
    state: started
    restart: yes
    env:
      LETSENCRYPT_EMAIL: 'thealiencyborg@gmail.com'
      LETSENCRYPT_HOST: 'biscuitmanchicago.com,www.biscuitmanchicago.com'
      VIRTUAL_HOST: 'biscuitmanchicago.com,www.biscuitmanchicago.com'

- name: pull and run biscuitman-test
  docker_container:
    name: biscuitman-test
    image: aliencyborg/biscuitman-test
    pull: true
    state: started
    restart: yes
    env:
      VIRTUAL_HOST: 'bm.aliencyb.org'
