---
- name: biscuitpress backups container
  docker_container:
    image: mariadb:10.2
    name: biscuitpress-db-backups
    state: present
    volumes:
      - /backups

- name: biscuitpress content container
  docker_container:
    image: wordpress:4.8
    name: biscuitpress-content
    state: present
    volumes:
      - /var/www/html

- name: biscuitpress data container
  docker_container:
    image: mariadb:10.2
    name: biscuitpress-db-data
    state: present
    volumes:
      - /var/lib/mysql

- name: biscuitpress db
  docker_container:
    env_file: biscuitpress.env
    image: mariadb:10.2
    name: biscuitpress-db
    state: started
    volumes_from:
      - biscuitpress-db-backups
      - biscuitpress-db-data

- name: biscuitpress web
  docker_container:
    env_file: biscuitpress.env
    exposed:
      - 80
      - 443
    image: wordpress:4.8
    name: biscuitpress-wp
    restart: yes
    state: started
    env:
      VIRTUAL_HOST: "bmpress.aliencyb.org"
      LETSENCRYPT_HOST: "bmpress.aliencyb.org"
      LETSENCRYPT_EMAIL: "thealiencyborg@gmail.com"
    links:
      - "biscuitpress-db:mysql"
    volumes_from:
      - biscuitpress-content

- name: biscuitpress ftp
  docker_container:
    command: biscuitman:$1$WwiP1eLk$cxIQPpxR4UzFIJ0hbaynC.:e:33:33
    image: atmoz/sftp:latest
    name: biscuitpress-ftp
    state: started
    ports:
      - "49222:22"
    volumes_from:
      - biscuitpress-content
