---
- name: pull and run bombaybreakdown
  docker_container:
    name: bombaybreakdown
    image: aliencyborg/bombaybreakdown
    pull: true
    state: started
    restart: yes
    env:
      LETSENCRYPT_EMAIL: 'thealiencyborg@gmail.com'
      LETSENCRYPT_HOST: 'bombaybreakdown.com,www.bombaybreakdown.com'
      VIRTUAL_HOST: 'bombaybreakdown.com,www.bombaybreakdown.com'
