---
- name: cogo-stage docker network
  docker_network:
    name: cogo-stage

- name: cogo-stage postgres backups container
  docker_container:
    image: postgres:9.6
    name: cogo-db-backups-stage
    state: present
    volumes:
      - /backups

- name: cogo-stage postgres data container
  docker_container:
    image: postgres:9.6
    name: cogo-db-data-stage
    state: present

- name: cogo-stage postgres
  docker_container:
    image: postgres:9.6
    name: cogo-db-stage
    state: started
    env:
      POSTGRES_USER: 'cogo'
      POSTGRES_PASSWORD: "{{ COGO_STAGE.POSTGRES_PASSWORD }}"
    exposed:
      - 5432
    networks:
      - name: cogo-stage
    volumes_from:
      - cogo-db-backups-stage
      - cogo-db-data-stage

- name: cogo-stage backer-upper
  docker_container:
    image: jmcarbo/docker-postgres-backup
    name: cogo-db-backer-upper-stage
    env:
      POSTGRES_HOST: 'pg'
    networks:
      - name: cogo-stage
        links:
          - "cogo-db-stage:pg"

- name: cogo-stage redis data container
  docker_container:
    image: redis:3.2
    name: cogo-redis-data-stage
    state: present

- name: cogo-stage redis
  docker_container:
    command: redis-server --requirepass "{{ COGO_STAGE.REDIS_PASSWORD }}"
    image: redis:3.2
    name: cogo-redis-stage
    state: started
    exposed:
      - 6379
    networks:
      - name: cogo-stage
    volumes_from:
      - cogo-redis-data-stage

- name: cogo-stage rails
  docker_container:
    env_file: cogo-stage.env
    image: aliencyborg/cogo-rails-stage
    name: cogo-rails-stage
    pull: true
    restart: yes
    state: started
    env:
      VIRTUAL_HOST: "cogomn.aliencyb.org"
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: "cogomn.aliencyb.org"
      LETSENCRYPT_EMAIL: "thealiencyborg@gmail.com"
    exposed:
      - 3000
    networks:
      - name: cogo-stage
        links:
          - "cogo-db-stage:postgres"
          - "cogo-redis-stage:redis"

- name: cogo-stage sidekiq
  docker_container:
    command: sidekiq -C config/sidekiq.yml.erb
    env_file: cogo-stage.env
    image: aliencyborg/cogo-rails-stage
    name: cogo-sidekiq-stage
    state: started
    networks:
      - name: cogo-stage
        links:
          - "cogo-db-stage:postgres"
          - "cogo-redis-stage:redis"
    volumes_from:
      - cogo-rails-stage

- name: cogo-stage action cable
  docker_container:
    command: puma -p 28080 cable/config.ru
    env_file: cogo-stage.env
    image: aliencyborg/cogo-rails-stage
    name: cogo-cable-stage
    state: started
    exposed:
      - 28080
    networks:
      - name: cogo-stage
        links:
          - "cogo-redis-stage:redis"
    volumes_from:
      - cogo-rails-stage

