---
- include: aliencyborg.yml
  become: yes
  become_user: root
  tags:
    - aliencyborg
    - webapps

- include: afsheen-fatemi.yml
  become: yes
  become_user: root
  tags:
    - afsheenfatemi
    - ghost

- include: biscuitman.yml
  become: yes
  become_user: root
  tags:
    - biscuitman
    - webapps

- include: biscuitpress.yml
  become: yes
  become_user: root
  tags:
    - biscuitpress
    - wordpress
    - webapps

- include: bombaybreakdown.yml
  become: yes
  become_user: root
  tags:
    - bombaybreakdown
    - webapps

- include: chucklove.yml
  become: yes
  become_user: root
  tags:
    - chucklove
    - webapps

- include: cogo.yml
  become: yes
  become_user: root
  tags:
    - cogo
    - webapps

- include: cogo-stage.yml
  become: yes
  become_user: root
  tags:
    - cogo-stage

- include: mwmoving.yml
  become: yes
  become_user: root
  tags:
    - mwmoving
    - webapps

- include: pics-api.yml
  become: yes
  become_user: root
  tags:
    - pics-api
    - webapps

- include: pretty-good.yml
  become: yes
  become_user: root
  tags:
    - pretty-good
    - ghost
    - webapps

- include: rosas-pics.yml
  become: yes
  become_user: root
  tags:
    - rosas-pics
    - webapps

- include: sudo-science.yml
  become: yes
  become_user: root
  tags:
    - sudoscience
    - ghost
    - webapps

- include: teeming-api.yml
  become: yes
  become_user: root
  tags:
    - teeming
    - teeming-api
    - ormn
    - webapps

- include: teeming-web.yml
  become: yes
  become_user: root
  tags:
    - teeming
    - teeming-web
    - ormn
    - webapps

- include: tilltax-demo.yml
  become: yes
  become_user: root
  tags:
    - tilltax-demo
    - webapps

- include: tilltax-preview.yml
  become: yes
  become_user: root
  tags:
    - tilltax-preview
    - webapps
