---
- name: otc-press backups container
  docker_container:
    image: mariadb:10.2
    name: otc-press-db-backups
    state: present
    volumes:
      - /backups

- name: otc-press content container
  docker_container:
    image: wordpress:4.9
    name: otc-press-content
    state: present
    volumes:
      - /var/www/html

- name: otc-press data container
  docker_container:
    image: mariadb:10.2
    name: otc-press-db-data
    state: present
    volumes:
      - /var/lib/mysql

- name: otc-press db
  docker_container:
    env_file: otc-press.env
    image: mariadb:10.2
    name: otc-press-db
    state: started
    volumes:
      - otc-press-db-backups:/backups
      - otc-press-db-data:/var/lib/mysql

- name: otc-press web
  docker_container:
    env_file: otc-press.env
    exposed:
      - 80
      - 443
    image: wordpress:4.9
    name: otc-press-wp
    restart: yes
    state: started
    env:
      LETSENCRYPT_EMAIL: 'ben@aliencyb.org'
      LETSENCRYPT_HOST: 'otcpress.aliencyb.org'
      VIRTUAL_HOST: 'otcpress.aliencyb.org'
    links:
      - "otc-press-db:mysql"
    volumes:
      - otc-press-content:/var/www/html

- name: otc-press ftp
  docker_container:
    command: otc:$1$ZtxZOIT/$6qA/Qsc/dHh5DKKKGJYiC1:33:33
    image: atmoz/sftp:latest
    name: otc-press-ftp
    state: started
    ports:
      - "49422:22"
    volumes:
      - otc-press-content:/home/otc/upload
