---
- name: pull and run rosas-pics
  docker_container:
    name: rosas-pics
    image: aliencyborg/rosas-pics-web:latest
    pull: true
    state: started
    restart: yes
    env:
      LETSENCRYPT_EMAIL: 'ben@aliencyb.org'
      LETSENCRYPT_HOST: 'rosas.pics,www.rosas.pics'
      VIRTUAL_HOST: 'rosas.pics,www.rosas.pics'
