---
- name: sudo-science backups container
  docker_container:
    image: mariadb:10.1
    name: sudo-science-db-backups
    state: present
    volumes:
      - /backups

- name: sudo-science content container
  docker_container:
    name: sudo-science-content
    image: aliencyborg/ghost-content
    pull: always
    state: present

- name: sudo-science data container
  docker_container:
    image: mariadb:10.1
    name: sudo-science-db-data
    state: present
    volumes:
      - /var/lib/mysql

- name: sudo-science db
  docker_container:
    env_file: .env
    image: mariadb:10.1
    name: sudo-science-db
    state: started
    volumes_from:
      - sudo-science-db-backups
      - sudo-science-db-data

- name: sudo-science web
  docker_container:
    env_file: .env
    expose: 2368
    image: ghost:0.11.4
    name: sudo-science-web
    restart: yes
    state: started
    env:
      VIRTUAL_HOST: 'sudo-science.com,www.sudo-science.com'
      LETSENCRYPT_HOST: 'sudo-science.com,www.sudo-science.com'
      LETSENCRYPT_EMAIL: 'thealiencyborg@gmail.com'
    links:
      sudo-science-db
    volumes_from:
      - sudo-science-content
