---
- name: pull and run tilltax-web
  docker_container:
    name: tilltax-web
    image: aliencyborg/tilltax-web
    pull: true
    state: started
    restart: yes
    env:
      LETSENCRYPT_EMAIL: 'thealiencyborg@gmail.com'
      LETSENCRYPT_HOST: 'tilltax.com,www.tilltax.com'
      VIRTUAL_HOST: 'tilltax.com,www.tilltax.com'
