---
- name: tilltax postgres data container
  docker_container:
    image: postgres:9.6
    name: tilltax-db-data
    state: present

- name: tilltax postgres
  docker_container:
    env_file: tilltax.env
    image: postgres:9.6
    name: tilltax-db
    state: started
    volumes_from:
      - tilltax-db-data

- name: tilltax api
  docker_container:
    env_file: tilltax.env
    image: aliencyborg/tilltax-api
    name: tilltax-api
    pull: true
    restart: yes
    state: started
    links:
      - "tilltax-db:db"
    env:
      VIRTUAL_HOST: "api.tilltax.com"
      LETSENCRYPT_HOST: "api.tilltax.com"
      LETSENCRYPT_EMAIL: "thealiencyborg@gmail.com"
