---
- name: pull and run vanadium
  docker_container:
    name: vanadium
    image: aliencyborg/aliencyborg-demo
    pull: true
    state: started
    restart: yes
    env:
      LETSENCRYPT_EMAIL: 'ben@aliencyb.org'
      LETSENCRYPT_HOST: 'vanadium.tech,www.vanadium.tech'
      VIRTUAL_HOST: 'vanadium.tech,www.vanadium.tech'
