---
- name: pull and run wastenot-web
  docker_container:
    name: wastenot-web
    image: aliencyborg/wastenot-web
    pull: true
    state: started
    restart: yes
    env:
      LETSENCRYPT_EMAIL: 'thealiencyborg@gmail.com'
      LETSENCRYPT_HOST: 'wastenotcompost.com,www.wastenotcompost.com'
      VIRTUAL_HOST: 'wastenotcompost.com,www.wastenotcompost.com'
