---
- name: wastenot postgres data container
  docker_container:
    name: wastenot-db-data
    image: postgres:9.5
    state: present

- name: wastenot postgres
  docker_container:
    name: wastenot-db
    image: postgres:9.5
    state: started
    volumes_from:
      - wastenot-db-data
    env:
      POSTGRES_DB: wastenot_prod
      POSTGRES_PASSWORD: wastenot_prod
      POSTGRES_USER: wastenot_prod

- name: wastenot api
  docker_container:
    name: wastenot-api
    image: aliencyborg/wastenot-api
    pull: true
    state: started
    restart: yes
    links:
      - wastenot-db
    env:
      DB_HOST: wastenot-db
      DB_PASSWORD: wastenot_prod
      DB_PORT: 5432
      DB_USER: wastenot_prod
      MIX_ENV: prod
      PORT: 80
      POSTGRES_DB: wastenot_prod
      SECRET_KEY_BASE: \
        MenagNznWdCpn3T0+V7VELazp71cx2MIyctOmgJ5x15BkLSO8GhMu666d2DpJX7t
      VIRTUAL_HOST: 'api.wastenotcompost.com'

- name: wastenot web
  docker_container:
    name: wastenot-web
    image: aliencyborg/wastenot-web
    pull: true
    state: started
    restart: yes
    env:
      VIRTUAL_HOST: 'wastenotcompost.com,www.wastenotcompost.com'
