---
- name: Run docker-gen container
  hosts: localhost
  become: True
  tasks:
    - name: ensure /usr/local/etc/nginx directory is present
      file:
        path: /usr/local/etc/nginx
        state: directory

    - name: copy nginx.tmpl file
      copy:
        src: nginx.tmpl
        dest: /usr/local/etc/nginx/nginx.tmpl

    - name: Pull and run docker-gen container
      docker_container:
        name: docker-gen
        image: jwilder/docker-gen
        volumes:
          - /usr/local/etc/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
          - /var/run/docker.sock:/tmp/docker.sock:ro
        volumes_from:
          - nginx-public
        entrypoint: "/usr/local/bin/docker-gen -notify-sighup nginx-public -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

