---
- name: Install and setup Docker
  hosts: localhost
  become: True
  tasks:
    - name: ensure the docker.service.d directory is present
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: copy docker.conf file
      copy:
        src: docker.conf
        dest: /etc/systemd/system/docker.service.d/docker.conf

    - name: install packages
      pacman:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker
          - docker-compose

    - name: docker service
      service:
        name: docker
        enabled: yes
        state: started

    - name: add user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

