---
- name: Run public nginx container
  hosts: localhost
  become: True
  tasks:
    - docker_container:
        name: nginx-public
        image: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /etc/nginx/certs
          - /etc/nginx/conf.d
          - /etc/nginx/vhost.d
          - /usr/share/nginx/html
