---
- name: Run nginx-proxy letsencrypt companion
  hosts: localhost
  become: True
  tasks:
    - docker_container:
        name: nginx-letsencrypt
        image: jrcs/letsencrypt-nginx-proxy-companion
        env:
          NGINX_DOCKER_GEN_CONTAINER: docker-gen
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
          - nginx-public
