---
- name: enable networkd
  service: name=systemd-networkd
   enabled=yes
   state=started

- name: enable sshd
  service: name=sshd.socket
    enabled=yes
    state=started

- name: configure wired network adapter
  template: src=wired.network
    dest=/etc/systemd/network/wired.network

- name: configure wireless network adapter
  template: src=wireless.network
    dest=/etc/systemd/network/wireless.network

- name: configure wpa_supplicant
  template: src=wpa_supplicant.conf
    dest=/etc/wpa_supplicant/wpa_supplicant-{{wireless_adapter}}.conf

- name: allow wpa_supplicant to update config files
  lineinfile: dest=/etc/wpa_supplicant/wpa_supplicant.conf
    regexp='update_config'
    line='update_config=1'

- name: check resolv.conf
  stat: path=/etc/resolv.conf
  register: resolvconf

- name: delete resolv.conf if not a link
  file: path=/etc/resolv.conf
    state=absent
  when: resolvconf.stat.islink is defined and resolvconf.stat.islnk == False

- name: link systemd to resolv.conf
  file: src=/run/systemd/resolve/resolv.conf
    dest=/etc/resolv.conf
    state=link

- name: enable wpa_supplicant
  service: name=wpa_supplicant@{{wireless_adapter}}
    enabled=yes
    state=started
