---
- name: install packages
  pacman: name={{ item }}
  tags:
    - packages
    - pacman
  with_items:
    - lightdm
    - mesa-libgl
    - xf86-video-intel
    - xmonad
    - xmonad-contrib
    - xorg-server

- name: enable lightdm
  service: name=lightdm
    enabled=yes

- name: ensure the .xmonad directory is present
  become_user: "{{ username }}"
  file: path=~/.xmonad
    state=directory


- name: copy haskell.hs to user home
  become_user: "{{ username }}"
  copy: src=xmonad.hs
    dest=~/.xmonad/xmonad.hs
    force=yes
