---
- name: ensure that ~/.config/systemd/user/default.target.wants directory is present
  file: path=~/.config/systemd/user/default.target.wants
    state=directory

- name: copy emacs.service to ~/.config/systemd/user
  copy: src=emacs.service
    dest=~/.config/systemd/user/emacs.service
    force=no

- name: create symlink for emacs.service
  file: src=/home/{{ username }}/.config/systemd/user/emacs.service
    dest=/home/{{ username }}/.config/systemd/user/default.target.wants/emacs.service
    state=link

- name: start emacs daemon
  command: systemctl --user start emacs
