---
- name: install packages
  pacman: name={{ item }}
    update_cache=yes
  with_items:
    - nodejs
    - npm

- name: install global node modules
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - brunch
    - ember-cli
    - httpster
    - jshint
