---
- name: install packages
  pacman: name={{ item }}
  become: yes
  become_method: sudo
  tags:
    - packages
    - pacman
  with_items:
    - nodejs
    - npm
    - phantomjs

- name: clone nvm
  git: repo=https://github.com/creationix/nvm.git
    dest=~/.nvm
    update=no

- name: set NVM_DIR in .zshrc
  lineinfile: dest=~/.zshrc
    regexp='export NVM_DIR'
    line='export NVM_DIR="$HOME/.nvm"'

- name: source nvm in .zshrc
  lineinfile: dest=~/.zshrc
    regexp='nvm\.sh'
    line='[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
