---
- name: install packages
  zypper: name={{ item }}
  with_items:
    - ack
    - ctags
    - curl
    - emacs
    - git
    - htop
    - openssh
    - tmux
    - unzip
    - vim
    - wget
  tags:
    - packages
