---
- name: perform full upgrade
  pacman: update_cache=yes upgrade=yes

- name: install packages
  pacman: name={{ item }}
  with_items:
    - nodejs
    - npm

- name: install global node modules
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - brunch
    - ember-cli
    - httpster
    - jshint
