---
- name: install packages
  pacman:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ack
      - ctags
      - curl
      - emacs
      - git
      - htop
      - jnettop
      - openssh
      - reflector
      - sudo
      - tmux
      - unzip
      - vim
      - wget