---
- name: ensure the docker.service.d directory is present
  file: path=/etc/systemd/system/docker.service.d
    state=directory

- name: copy docker.conf file
  copy: src=docker.conf
    dest=/etc/systemd/system/docker.service.d/docker.conf

- name: install packages
  pacman: name={{ item }}
  tags: packages
  with_items:
    - docker
    - python2-docker-py

- name: docker service
  service: name=docker
    enabled=yes
    state=started

- name: add user to docker group
  user: name={{ username }}
    groups=docker
    append=yes

- name: restart the machine
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for the machine to come back online
  local_action: wait_for host={{ inventory_hostname }}
    search_regex=OpenSSH
    port={{ ansible_port }}
    timeout=300
