---
- name: run nginx-proxy docker container
  docker:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    ports: 80:80
    state: started
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
