---
- name: check if .vim exists
  stat: path=~/.vim
  register: vim_dir

- name: check if .vim is a git repo
  when: vim_dir.stat.exists
  stat: path=~/.vim/.git
  register: vim_git

- name: backup .vim if it's not a repo
  when: (vim_dir.stat.exists and vim_git.stat.isdir is not defined)
  command: mv ~/.vim ~/.vim.backup

- name: clone janus
  git: repo=https://github.com/carlhuda/janus.git
    dest=~/.vim
    update=no

- name: rake janus
  shell: cd ~/.vim && rake

- name: copy vimrc.after to user home
  copy: src=vimrc.after
    dest=~/.vimrc.after
    force=no

- name: ensure the .janus directory is present
  file: path=~/.janus
    state=directory

- name: clone abolish submodule
  shell: cd ~/.janus && git init && git submodule add
    https://github.com/tpope/vim-abolish.git abolish
    creates=~/.janus/abolish

- name: clone vim-colorschemes submodule
  shell: cd ~/.janus && git submodule add
    https://github.com/flazz/vim-colorschemes.git colorschemes
    creates=~/.janus/colorschemes

- name: clone javascript-libraries-syntax submodule
  shell: cd ~/.janus && git submodule add
    https://github.com/othree/javascript-libraries-syntax.vim.git
    javascript-libraries-syntax
    creates=~/.janus/javascript-libraries-syntax

- name: clone oceanic-next submodule
  shell: cd ~/.janus && git submodule add
    https://github.com/yosiat/oceanic-next-vim.git oceanic-next-vim
    creates=~/.janus/oceanic-next-vim

- name: clone tabular submodule
  shell: cd ~/.janus && git submodule add
    https://github.com/godlygeek/tabular.git tabular
    creates=~/.janus/tabular

- name: clone yajs submodule
  shell: cd ~/.janus && git submodule add
    https://github.com/othree/yajs.vim.git yajs
    creates=~/.janus/yajs
