- name: Run acme-companion container
  docker_container:
    name: nginx-proxy-acme
    image: nginxproxy/acme-companion:latest
    pull: true
    restart_policy: always
    env:
      DEFAULT_EMAIL: "{{ ADMIN_EMAIL }}"
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    volumes:
      - nginx_acme:/etc/acme.sh
      - nginx_certs:/etc/nginx/certs
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
