---
- name: ensure the docker.service.d directory is present
  file: path=/etc/systemd/system/docker.service.d
    state=directory

- name: copy docker.conf file
  copy: src=docker.conf
    dest=/etc/systemd/system/docker.service.d/docker.conf

- name: install packages
  pacman: name={{ item }}
  tags:
    - packages
    - pacman
  with_items:
    - docker
    - docker-compose
    - python2-docker-py

- name: docker service
  service: name=docker
    enabled=yes
    state=started

- name: add user to docker group
  user: name={{ username }}
    groups=docker
    append=yes
