- name: Run docker-gen container
  docker_container:
    name: nginx-proxy-gen
    image: nginxproxy/docker-gen:latest
    pull: true
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_vhost.d:/etc/nginx/vhost.d
      - nginx_certs:/etc/nginx/certs:ro
    entrypoint: >
      /usr/local/bin/docker-gen
      -notify-sighup nginx-proxy
      -watch
      /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - name: proxy_network
