---
- name: ensure that the mail-config directory is present
  file: path=~/maild-config
    state=directory

- name: setup mail server with docker
  docker_service:
    project_name: mailserver
    definition:
      version: '2'
      services:
        mail:
          image: tvial/docker-mailserver:latest
          hostname: mail
          domainname: aliencyb.org
          container_name: mail
          ports:
            - "25:25"
            - "143:143"
            - "587:587"
            - "993:993"
          volumes:
            - maildata:/var/mail
            - ~/mail-config:/tmp/docker-mailserver/

      volumes:
        maildata:
          driver: local

- name: create mail accounts
  command: docker run --rm
    -e MAIL_USER={{ mail_user }}
    -e MAIL_PASS={{ mail_pass }}
    -ti tvial/docker-mailserver:latest /bin/sh -c
    'echo "$MAIL_USER|$(doveadm pw -s CRAM-MD5 -u $MAIL_USER -p $MAIL_PASS)"'
    >> config/postfix-accounts.cf

