---
- name: Run nginx-proxy letsencrypt companion
  docker_container:
    image: jrcs/letsencrypt-nginx-proxy-companion
    name: nginx-proxy-letsencrypt
    env:
      DEBUG: "true"
      DEFAULT_EMAIL: "{{ ADMIN_EMAIL }}"
      NGINX_DOCKER_GEN_CONTAINER: "nginx-proxy-gen"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

