- name: Run public-facing nginx-proxy container
  docker_container:
    name: nginx-proxy
    image: nginxproxy/nginx-proxy:latest
    pull: true
    restart_policy: always
    env:
      RESOLVERS: "8.8.8.8 8.8.4.4"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhost.d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - name: proxy_network
