---
- name: Run nginx-proxy letsencrypt companion
  docker_container:
    image: jrcs/letsencrypt-nginx-proxy-companion
    name: nginx-proxy-letsencrypt
    env:
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
      DEFAULT_EMAIL: "{{ ADMIN_EMAIL }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

