---
- name: Run nginx-proxy letsencrypt companion
  docker_container:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    name: nginx-proxy-letsencrypt
    pull: true
    recreate: yes
    restart_policy: always
    env:
      # uncomment for letsencrypt dry-run:
      #ACME_CA_URI: "{{ ACME_STAGE_URI }}"
      DEBUG: "{{ LETSENCRYPT_DEBUG }}"
      DEFAULT_EMAIL: "{{ ADMIN_EMAIL }}"
      NGINX_DOCKER_GEN_CONTAINER: "nginx-proxy-gen"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

