---
- name: Run public-facing nginx-proxy container
  docker_container:
    image: nginx:latest
    name: nginx-proxy
    pull: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html