---
- name: ensure /usr/local/etc/packetbeat directory is present
  file:
    path: /usr/local/etc/packetbeat
    state: directory

- name: copy heartbeat.docker.yml file
  copy:
    src: heartbeat.docker.yml
    dest: /usr/local/etc/packetbeat

- name: copy packetbeat.docker.yml file
  copy:
    src: packetbeat.docker.yml
    dest: /usr/local/etc/packetbeat

- name: ensure elasticsearch data volume
  docker_container:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    name: packetbeat-es-data
    state: stopped
    volumes:
      - /usr/share/elasticsearch/data

- name: pull and run elasticsearch container
  docker_container:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    name: packetbeat-es
    recreate: yes
    restart_policy: always
    env:
      "discovery.type": "single-node"
      #LETSENCRYPT_HOST: "es.aliencyb.org"
      VIRTUAL_HOST: "es.aliencyb.org"
      VIRTUAL_PORT: "9200"
    exposed_ports:
      - "9200:9200"
      - "9300:9300"
    published_ports:
      - "9200:9200"
      - "9300:9300"
    volumes_from:
      - packetbeat-es-data

- name: pull and run kibana
  docker_container:
    image: docker.elastic.co/kibana/kibana:7.7.0
    name: packetbeat-kibana
    published_ports:
      - "5601:5601"
    recreate: yes
    restart_policy: always
    env:
      ELASTICSEARCH_HOSTS: "http://packetbeat-es:9200"
      #LETSENCRYPT_HOST: "kibana.aliencyb.org"
      #SERVER_HOST: "kibana.aliencyb.org"
      SERVER_NAME: "packetbeat-kibana"
      VIRTUAL_HOST: "kibana.aliencyb.org"
      VIRTUAL_PORT: "5601"
    exposed_ports:
      - "5601:5601"
    links:
      - "packetbeat-es:elasticsearch"

- name: pull and run heartbeat
  docker_container:
    command: "--strict.perms=false -e -E output.elasticsearch.hosts=['elasticsearch:9200']"
    image: docker.elastic.co/beats/heartbeat:7.7.0
    name: packetbeat-heartbeat
    restart_policy: always
    user: heartbeat
    links:
      - "packetbeat-es:elasticsearch"
      - "packetbeat-kibana:kibana"
    volumes:
      - /usr/local/etc/packetbeat/heartbeat.docker.yml:/usr/share/packetbeat/heartbeat.docker.yml:ro

- name: pull and run packetbeat setup
  docker_container:
    command: "--strict.perms=false -e -E output.elasticsearch.hosts=['http://es.aliencyb.org:59200']"
    image: docker.elastic.co/beats/packetbeat:7.7.0
    name: packetbeat
    network_mode: host
    recreate: yes
    user: packetbeat
    capabilities:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /usr/local/etc/packetbeat/packetbeat.docker.yml:/usr/share/packetbeat/packetbeat.docker.yml:ro

