- name: restart the machine
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for the machine to come back online
  local_action: wait_for host={{ inventory_hostname }}
    search_regex=OpenSSH
    port={{ ansible_port }}
    timeout=300
