---
- name: perform full upgrade
  pacman: update_cache=yes upgrade=yes

- name: install packages
  pacman: name={{ item }}
  tags: packages
  with_items:
    - ack
    - ansible
    - ctags
    - curl
    - git
    - htop
    - openssh
    - ruby
    - tmux
    - vim
    - wget
    - zsh
