---
- name: pull and run cooperage with docker-compose
  docker_service:
    project_name: cooperage
    definition:
      version: '2'
      services:
        api:
          image: aliencyborg/cooperage-api:latest
          container_name: cooperage-api
          env:
            VIRTUAL_HOST: 'api.cuperygroup.com'
          env_file:
            - ./cooperage.env
          expose: 80
          links:
            - db
        db:
          image: postgres:9.4
          container_name: cooperage-db
          env_file:
            - ./cooperage.env
          volumes:
            - data:/var/lib/postgresql/data
      volumes:
        data: {}
